apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-kwixeerdbms-com
spec:
  secretName: wildcard-kwixeerdbms-com-tls
  renewBefore: 240h
  dnsNames:
  - '*.kwixeerdbms.com'
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer