kind: Ingress
metadata:
  name: jeevantestadminapi-kwixeerdbms-com-ingress
  namespace: quixy-api
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - jeevantestadminapi.kwixeerdbms.com
    secretName: wildcard-kwixeerdbms-com-tls
  rules:
  - host: jeevantestadminapi.kwixeerdbms.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: adminapi
            port:
              number: 5000